### ISSUE TITLE
Grundpaket: Epic Basissystem für JEMK

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_jemk#1]
Ziel: Aufbau Grundpaket/Umgebung für die Jungschar EMK

Inhalt:

- [x] Neues Repo erstellen: hitobito_kunde About ergänzen
- [x] Wagon erstellen #4 
- [x] Setup der Integrationsumgebung #2 
- [x] Gruppenstruktur, Rollen, Berechtigungen #5 
- [x] Visuelle Anpassungen #6 
- [x] Resourcen bestellen bei /sys
- [x] Mehrsprachigkeit #7 
- [x] Produktionsumgebung #3 
- [x] Root-User-Password in Cryptopus legen
- [x] Github Actions
- [x] DNS Einstellungen Kundenseite
- [x] Wartung und Support
