### ISSUE TITLE
EVENTS: Lager Anmeldungen können nicht aufgelistet werden

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_jemk#20]
### Aktuelles Verhalten

Ist bei einem Lager mind. eine Person auf der Warteliste, so können die Anmeldungen nicht mehr aufgelistet werden.

![image](https://github.com/hitobito/hitobito_jemk/assets/655627/dacf056a-c379-4335-8151-d87fbc11be6f)

500 Server Error

### Gewünschtes Verhalten

Die Anmeldungen eines Lagers können euch mit Personen auf der Warteliste aufgelistet werden.

### Schritte zu reproduzieren

1. Neues Lager erstellen oder bestehendes öffnen
2. Beliebige Peson auf die Warteliste des Lagers setzen
3. Auf Tab Anmeldungen klicken
4. :boom: 

### hitobito version

2.0.4

### Organisation

JEMK

### Screenshots, weiterer Kontext

```
ActionView::Template::Error

undefined method `kind' for #<EventDecorator:0x00007f470f3b23a8 @object=#<Event::Camp id: 64, type: "Event::Camp", number: nil, motto: "", cost: "", maximum_participants: nil, contact_id: nil, location: "", application_opening_at: nil, application_closing_at: nil, kind_id: nil, state: nil, priorization: false, requires_approval: false, created_at: "2024-03-04 09:06:34.000000000 +0100", updated_at: "2024-03-04 09:07:10.000000000 +0100", participant_count: 0, application_contact_id: nil, external_applications: true, applicant_count: 1, teamer_count: 0, signature: false, signature_confirmation: false, creator_id: 1, updater_id: 1, applications_cancelable: true, required_contact_attrs: [], hidden_contact_attrs: [], display_booking_info: true, participations_visible: false, waiting_list: true, globally_visible: true, shared_access_token: "byH-QzvuNRqxyr1bFuo1", notify_contact_on_participations: false, training_days: nil, tentative_applications: false, application_conditions: nil, description: nil, name: "Testlager PSI", signature_confirmation_text: "Erziehungsberechtigte Person (bei Minderjährigen)", tag_list: nil>, @context={}, @translation_prefix="event_decorator">
```

https://sentry.puzzle.ch/pitc/hitobito-backend/issues/66707/

### ToDos

- [x] Analyse warum Event Kind benötigt wird
- [x] Spec für Auflistung Anmeldungen schreiben
- [x] Problem im JEMK Wagon fixen
